# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

#theme                    : "minimal-mistakes-jekyll"
#remote_theme           : "mmistakes/minimal-mistakes"
remote_theme: "mmistakes/minimal-mistakes@4.16.3"
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "LF2L"
title_separator          : "|"
name                     : "LF2L Team"
description              : "Site of the Lorraine Fab Living Lab (LF2L)."
url                      : "http://lf2l.fr"
baseurl                  : ""  #/LF2L" # the subpath of your site, e.g. "/blog"
repository               : "LF2L/lf2l.github.io" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200
comments:
  provider               : # false (default), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "custom"
  disqus:
    shortname            : # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
  utterances:
    theme                : # "github-light" (default), "github-dark"
    issue_term           : # "pathname" (default)
staticman:
  allowedFields          : # ['name', 'email', 'url', 'message']
  branch                 : # "master"
  commitMessage          : # "New comment by {fields.name}"
  filename               : # comment-{@timestamp}
  format                 : # "yml"
  moderation             : # true
  path                   : # "/_data/comments/{options.slug}" (default)
  requiredFields         : # ['name', 'email', 'message']
  transforms:
    email                : # "md5"
  generatedFields:
    date:
      type               : # "date"
      options:
        format           : # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
  endpoint               : # URL of your own deployment with trailing slash, will fallback to the public instance
reCaptcha:
  siteKey                :
  secret                 :
atom_feed:
  path                   : # blank (default) uses feed.xml
search                   : # true, false (default)
search_full_content      : # true, false (default)
search_provider          : # lunr (default), algolia, google
algolia:
  application_id         : # YOUR_APPLICATION_ID
  index_name             : # YOUR_INDEX_NAME
  search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : # true (default), false
google:
  search_engine_id       : # YOUR_SEARCH_ENGINE_ID
  instant_search         : # false (default), true
# SEO Related
google_site_verification :
bing_site_verification   :
yandex_site_verification :
naver_site_verification  :

# Social Sharing
twitter:
  username               :
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider               : false # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          :
    anonymize_ip         : # true, false (default)



# Site Author
author:
  name             : "Lorraine Fab Living Lab"
  avatar           : # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "Innovation in 4D"
  location         : "Nancy"
  email            :
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      # url: mailto:your.name@email.com
    - label: "Website"
      icon: "fas fa-fw fa-link"
      # url: "https://your-website.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      # url: "https://twitter.com/"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url: "https://facebook.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      # url: "https://github.com/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url: "https://instagram.com/"

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      # url:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      # url:
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      # url:
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"
      # url:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url:


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: #/:categories/:title/
paginate: #5 # amount of posts to show
paginate_path: #/page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# Languages

languages:
  -
    -
    - English
  -
    - fr
    - Fran√ßais


# Directories
collections_dir: collections
layouts_dir: _jekyll/_layouts
includes_dir: _jekyll/_includes

# Collections
collections:
  concept:
    output: true
    permalink: /:collection/:path/

  communities:
    output: true
    permalink: /:collection/:path/

  place-tools:
    output: true

  info:
    output: true

  posts:
    output: true
    permalink: /:collection/:year/:month/:day/:title/

  publications:
    output: true
    permalink: /:path/
  
  projects:
    output: true
    permalink: /:collection/:path/
  
  people:
    output: true
    permalink: /:collection/:path/
  
  green-fablab:
    output: true
    permalink: /:collection/:path/

  tutorial:
    output: true
    permalink: /:collection/:path/


# Defaults

defaults:

  # default
  - scope:
      path: ""
    values:
      lang: en
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false
      sidebar:
        nav: ""

    # CONCEPT
  - scope:
      path: concept
    values:
      layout: single

    # CONCEPT - EN
  - scope:
      path: "_concept/en"
    values:
      lang: en
    # CONCEPT - FR
  - scope:
      path: "_concept/fr"
    values:
      lang: fr


  # PROJECTS
  - scope:
      type: projects
    values:
      layout: single
      sidebar:
        nav: ""
    
    # PROJECTS EN
  - scope:
      path: "_projects/en"
    values:
      lang: en
      sidebar:
        nav: "projects"
    
    # PROJECTS FR
  - scope:
      path: "_projects/fr"
    values:
      lang: fr
      sidebar:
        nav: "projects"


    # COMMUNITIES
  - scope:
      type: communities
    values:
      layout: single
      classes: wide
      sidebar:
        nav: "communities"

    # COMMUNITIES - EN
  - scope:
      path: "_communities/en"
    values:
      lang: en
      sidebar:
        nav: communities


    # COMMUNITIES - FR
  - scope:
      path: "_communities/fr"
    values:
      lang: fr
      sidebar:
        nav: communities

    # PLACE & TOOLS
  - scope:
      type: place-tools
    values:
      layout: single
      sidebar:
        nav: "place_tools"

    #  PLACE & TOOLS - EN
  - scope:
      path: "_place-tools/en"
    values:
      lang: en


    #  PLACE & TOOLS - FR
  - scope:
      path: "_place-tools/fr"
    values:
      lang: fr

    # PRACTICAL INFO
  - scope:
      type: info
    values:
      layout: single
      sidebar:
        nav: "info"

    #  PRACTICAL INFO - EN
  - scope:
      path: "_info/en"
    values:
      lang: en

    # PRACTICAL INFO - FR
  - scope:
      path: "_info/fr"
    values:
      lang: fr


  # POST folder
  - scope:
      type: posts
    values:
      layout: single
      is_post: true
      share: true
      read_time: true
      related: false
      sidebar:
        nav: ""
    
    # POST EN
  - scope:
      path: "_posts/en"
    values:
      lang: en

    # POST FR  
  - scope:
      path: "_posts/fr"
    values:
      lang: fr           
      permalink: /fr/:collection/:year/:month/:day/:title/


    # GREEN FABLAB COLLECTION Folder
  - scope:
      type: green-fablab
    values:
      layout: single
      sidebar:
        nav: "Green-Fablab"

    # GREEN FABLAB COLLECTION - EN
  - scope:
      path: "_green-fablab/en"
    values:
      lang: en

    # GREEN FABLAB COLLECTION - FR
  - scope:
      path: "_green-fablab/fr"
    values:
      lang: fr

# PEOPLE COLLECTION
  - scope:
      type: people
    values:
      layout: single
      author_profile: true

    #en
  - scope:
      path: "_people/en"
    values:
      lang: en
    #fr
  - scope:
      path: "_people/fr"
    values:
      lang: fr



    # TUTORIALS COLLECTION
  - scope:
      type: tutorial
    values:
      layout: single
     

    # Tutorials Folder - EN
  - scope:
      path: "_tutorial/en"
    values:
      lang: en
      sidebar:
        nav: tutorials


    # Tutorials Folder - FR
  - scope:
      path: "_tutorial/fr"
    values:
      lang: fr
      sidebar:
        nav: tutorials


  # # _pages Main Pages of the site
  # - scope:
  #     type: pages
  #   values:
  #     sidebar:
  #       nav: ""
  #   # en
  # - scope:
  #     path: "_pages/en"
  #   values:
  #     lang: en
  #   # de
  # - scope:
  #     path: "_pages/fr"
  #   values:
  #     lang: fr





# footer_scripts:
#   - //ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js
#   - /assets/js/vendor/jquery/jquery-3.2.1.min.js
#   - /assets/js/plugins/jquery.fitvids.js
#   - /assets/js/plugins/jquery.greedy-navigation.js
#   - /assets/js/plugins/jquery.magnific-popup.js
#   - /assets/js/plugins/jquery.smooth-scroll.min.js
#   - /assets/js/plugins/_main.js
#   - /assets/js1/flexslider/jquery.flexslider-min.js
#   - /assets/js1/app.js

# It'd be nice to have "lang" set through wildcard, using * for directories:
# https://jekyllrb.com/docs/configuration/front-matter-defaults/
# this doesn't seem to work
# e.g.:
#  - scope:
#      path: "*/de"
#    values:
#      lang: de





# The Reveal theme
reveal_theme: black.css

# The Reveal transition
reveal_transition: default

# Path to the used theme (defaults to the Reveal.js standard theme path)
reveal_theme_path: reveal.js/css/theme/ 

# Additional custom CSS paths
extra_css: 

# Custom CSS for highlighting (defaults to reveal.js/lib/css/zenburn.css)
highlight_style_sheet: 

# Embed Server-side speaker notes?
reveal_notes_server: false

# Additional reveal.js options
reveal_options: 

# Additional reveal.js dependencies
reveal_dependencies: 

# Reveal.js subdirectory
reveal_path: reveal.js/

# # Exclude directories and/or files from the conversion
# exclude:
#   - Gemfile*
#   - LICENSE
#   - README.md

# Don't change anything below
#markdown: kramdown
#highlighter: rouge
#markdown_ext: ignoreme










